verifier:
  metaData:
    clientName: "LicenceCheck (Local)"
  mock:
    failResponse: false
    errorCode: CREDENTIAL_INVALID

jeap:
  swagger:
    status: OPEN

cors:
  allowed-origins:
    - 'http://localhost:8888'
    - 'http://localhost:4201'
    - 'http://127.0.0.1:8888'
    - 'http://127.0.0.1:4201'

verifier-agent-management:
  endpoint: "MOCKED"

springdoc:
  swagger-ui:
    enabled: true
