spring:
  application:
    name: vz-licencecheck-scs

jeap:
  swagger:
    status: DISABLED
  web:
    headers:
      content-security-policy: "default-src 'self' *.admin.ch; script-src 'self' 'unsafe-inline' *.admin.ch; style-src 'self' 'unsafe-inline'; frame-src 'self' *.admin.ch; img-src 'self' data:;"

server:
  port: 8888
  servlet:
    context-path: /
  compression:
    enabled: true
  #Increase the max header size as token can be quite big. 4MB should be enough for ~100'000 Roles for one user, normally this should be plenty
  max-http-request-header-size: 4MB

verifier:
  allowed-issuer-did: ${ALLOWED_ISSUER_DID}
  use-case-folderPath: "use-cases"

management:
  endpoint:
    health:
      probes:
        enabled: true

springdoc:
  swagger-ui:
    enabled: false
    oauth:
      client-id: astra-vz-licencecheck-swagger
  default-produces-media-type: application/json
  show-actuator: true

# default logging level
logging:
  level:
    root: info

verifier-agent-management:
  endpoint: "${VERIFIER_SERVICE_ENDPOINT}"
  logging:
    level: NONE # "NONE", "BASIC", "HEADERS", "BODY"