verifier:
  allowed-issuer-did: "MOCK-DID"
  client-name: "LicenceCheck (Local)"
  mock:
    failResponse: false
    errorCode: JWT_PREMATURE

jeap:
  swagger:
    status: OPEN

cors:
  allowed-origins:
    - 'http://localhost:8888'
    - 'http://localhost:4201'
    - 'http://127.0.0.1:8888'
    - 'http://127.0.0.1:4201'

springdoc:
  swagger-ui:
    enabled: true

features:
  use-single-verifier-enabled: true
